<a href="https://colab.research.google.com/github/Anubrata-Mallick/ML_Tools/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**System specification**

In [ ]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed bhi
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
ad

**NumPy - Numerical Python**

Advantages of Numpy Arrays :
  1. Allows several mathametical operation
  2. Faster Operation

In [ ]:
import numpy as np

**List vs Numpy - Time Takekn**

In [ ]:
from time import process_time

In [ ]:
# Time taken by List

python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0014719819999999828


In [ ]:
# Time taken by Numpy Array

np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0008666290000007848


**Numpy Array**

In [ ]:
#list

list1 = [1, 2, 3, 4, 5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1, 2, 3, 4, 5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

**Initial PlaceHolders in numpy arrays**

In [ ]:
# create numpy array of zero
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create numpy arrays of ones
y = np.ones((3, 3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# array for perticular value
z = np.full((5, 4), 22)
print(z)

[[22 22 22 22]
 [22 22 22 22]
 [22 22 22 22]
 [22 22 22 22]
 [22 22 22 22]]


In [ ]:
# create an Identity Matrix
a = np.identity(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# create numpy array with random value

b = np.random.random((3, 4))
print(b)

[[0.92040397 0.06649478 0.43308641 0.44159932]
 [0.91518779 0.25570975 0.76935829 0.61622237]
 [0.25648025 0.94861949 0.88354737 0.66556397]]


In [ ]:
# Random Integer values array within a specific range
c = np.random.randint(10, 100, (3,5))
print(c)

[[72 90 22 52 98]
 [93 86 32 88 26]
 [41 17 56 74 23]]


In [ ]:
# array of evenly spaced values --> specify the number of values required
d = np.linspace(10, 30, 6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
# Array of evenly spaced value --> specify the step
e = np.arange(10, 30, 5)
print(e)

[10 15 20 25]


In [ ]:
# Convert a list to an numpy array
list2 = [10, 20, 30]

np_array = np.asarray(list2)

print(np_array)
type(np_array)

[10 20 30]


numpy.ndarray

**Analysing a Numpy Array**

In [ ]:
c = np.random.randint(10, 90, (5,5))
print(c)

[[84 41 20 14 46]
 [33 53 73 29 33]
 [55 81 86 43 11]
 [54 28 47 41 43]
 [73 24 50 41 12]]


In [ ]:
# array diamention
print(c.shape)

(5, 5)


In [ ]:
#number of dimension
print(c.ndim)

2


In [ ]:
# number of elements in an array
print(c.size)

25


In [ ]:
# check data type of the values in array
print(c.dtype)

int64


**Mathematical Operations on a np array**

In [ ]:
list1 = [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]

print(list1 + list2) # will concat 2 list not adding

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0, 10, (3, 3))
b = np.random.randint(0, 10, (3, 3))

print("Addition = ", np.add(a, b))
print("Subtract = ", np.subtract(a, b))
print("Multiply = ", np.multiply(a, b))
print("Devide = ", np.divide(a, b))

Addition =  [[12  6  7]
 [ 6  9 13]
 [ 9  6  4]]
Subtract =  [[ 6 -6  7]
 [ 4  7 -1]
 [ 7 -4  0]]
Multiply =  [[27  0  0]
 [ 5  8 42]
 [ 8  5  4]]
Devide =  [[3.         0.                inf]
 [5.         8.         0.85714286]
 [8.         0.2        1.        ]]


<ipython-input-32-e6946a1948e7>:7: RuntimeWarning: divide by zero encountered in divide
  print("Devide = ", np.divide(a, b))


**Array Manipulation**

In [ ]:
array = np.random.randint(0, 10, (2, 3))
print(array)
print(array.shape)

[[8 5 6]
 [1 3 7]]
(2, 3)


In [ ]:
# Transpose

trans = np.transpose(array) # it can also be done by trans = array.T
print(trans)
print(trans.shape)

[[8 1]
 [5 3]
 [6 7]]
(3, 2)


In [ ]:
# Reshaping an Array

a = np.random.randint(0, 10, (2, 3))
print(a)
print(a.shape)

[[3 5 9]
 [0 4 3]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[3 5]
 [9 0]
 [4 3]]
(3, 2)
